# Fuzzy Membership Finetuning

Fine-tunes a small BERT model on soft (fuzzy) cluster membership vectors using
the `fuzzyfinetuning_crossentropy.py` script from the RecsysUpgrade repo.

Reads the membership matrix saved by the clustering notebook (`fkmeans_memberships.csv`
and `fkmeans_clusters.csv`) from the same `CLUSTERS_OUTPUT_DIR`.

### Step 1: Setup (drive mounting, paths)

In [1]:
from google.colab import drive
import os

drive.mount('/content/drive')

# ── Match these paths to clustering_comparison.ipynb ──────────────────────────
DRIVE_BASE          = "/content/drive/MyDrive/S2026/Spotify Playlist Data/Processed Data/calced_embeddings"
PROJECT_BASE        = "/content/drive/MyDrive/S2026/CS 274/Playlist-Recommender"
EMBEDDINGS_PKL      = f"{DRIVE_BASE}/mean_pooled_embeddings.pkl"
CLUSTERS_OUTPUT_DIR = f"{PROJECT_BASE}/new clusters"
# ──────────────────────────────────────────────────────────────────────────────

FINETUNED_MODEL_DIR = f"{PROJECT_BASE}/fuzzy_finetuned_model"
REPO_DIR            = "/content/RecsysUpgrade"

os.makedirs(FINETUNED_MODEL_DIR, exist_ok=True)
print("Paths configured.")

Mounted at /content/drive
Paths configured.

### Step 2: Clone repo and install requirements

In [2]:
if not os.path.exists(REPO_DIR):
    !git clone https://github.com/siddmohanty111/RecsysUpgrade.git {REPO_DIR}
else:
    !git -C {REPO_DIR} pull

print("Repo ready:", REPO_DIR)

Cloning into '/content/RecsysUpgrade'...
remote: Enumerating objects: 105, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 105 (delta 53), reused 64 (delta 24), pack-reused 0 (from 0)
Receiving objects: 100% (105/105), 1.49 MiB | 39.03 MiB/s, done.
Resolving deltas: 100% (53/53), done.
Repo ready: /content/RecsysUpgrade

In [3]:
%pip install -r {REPO_DIR}/requirements.txt -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 920.8/920.8 kB 72.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 116.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 763.1/763.1 kB 69.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 79.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 548.1/548.1 kB 55.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 10.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 6.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

### Step 3: Load membership matrix and playlist titles

In [3]:
import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# fkmeans_clusters.csv was saved alongside fkmeans_memberships.csv from the same `pids` list,
# so row i in memberships corresponds to row i (pid) in clusters.
clusters_df = pd.read_csv(
    os.path.join(CLUSTERS_OUTPUT_DIR, "fkmeans_clusters.csv"),
    dtype={"pid": str},
)
pids_ordered = clusters_df["pid"].tolist()

memberships_df = pd.read_csv(os.path.join(CLUSTERS_OUTPUT_DIR, "fkmeans_memberships.csv"))
membership_cols = [c for c in memberships_df.columns if c.startswith("cluster_")]
num_clusters = len(membership_cols)
print(f"Membership matrix: {len(pids_ordered)} playlists × {num_clusters} clusters")

# Load playlist titles from the embeddings pkl (same source as the clustering notebook)
with open(EMBEDDINGS_PKL, "rb") as f:
    raw_data = pickle.load(f)

playlist_titles = (
    raw_data.get("playlist_titles", {})
    if isinstance(raw_data, dict)
    else {}
)
print(f"Playlist titles available: {len(playlist_titles)}")

Membership matrix: 1000001 playlists × 50 clusters
Playlist titles available: 1000001

### Step 4: Build dataset and train/val split

In [5]:
# Build a DataFrame with the two columns expected by fuzzyfinetuning_crossentropy.run():
#   "Playlist Title"  — string title
#   "Cluster Labels"  — string repr of a Python list, e.g. "[0.12, 0.03, ...]"
#                       (parsed by ast.literal_eval inside the finetuning script)

data_df = pd.DataFrame({
    "Playlist Title": [playlist_titles.get(pid, "") for pid in pids_ordered],
    "Cluster Labels": memberships_df[membership_cols].values.tolist(),
})

# Convert each membership list to its string representation
data_df["Cluster Labels"] = data_df["Cluster Labels"].apply(str)

# Drop playlists with no title — they carry no signal for the model
data_df = data_df[data_df["Playlist Title"].str.strip() != ""].reset_index(drop=True)
print(f"Dataset after dropping untitled playlists: {len(data_df)}")

# 90 / 10 train–val split
train_df, val_df = train_test_split(data_df, test_size=0.1, random_state=42)

TRAIN_CSV = os.path.join(CLUSTERS_OUTPUT_DIR, "fuzzy_train.csv")
VAL_CSV   = os.path.join(CLUSTERS_OUTPUT_DIR, "fuzzy_val.csv")

train_df.to_csv(TRAIN_CSV, index=False)
val_df.to_csv(VAL_CSV,   index=False)
print(f"Train: {len(train_df)}  Val: {len(val_df)}")
print(f"Saved to {CLUSTERS_OUTPUT_DIR}")

Dataset after dropping untitled playlists: 1000001
Train: 900000  Val: 100001
Saved to /content/drive/MyDrive/S2026/CS 274/Playlist-Recommender/new clusters

### Step 5: Load finetuning module and run

In [7]:
import importlib.util

ft_path = os.path.join(
    REPO_DIR, "PlaylistRecsysUpgrade", "finetuning", "fuzzyfinetuning_crossentropy.py"
)
spec   = importlib.util.spec_from_file_location("fuzzyfinetuning_crossentropy", ft_path)
fuzzy_ft = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fuzzy_ft)
print("fuzzyfinetuning_crossentropy loaded.")

fuzzyfinetuning_crossentropy loaded.

In [7]:
# Using MiniLM for better quality embeddings
fuzzy_ft.run(
    train_csv=TRAIN_CSV,
    val_csv=VAL_CSV,
    output_dir=FINETUNED_MODEL_DIR,
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    batch_size=128,
    epochs=20,
    learning_rate=3e-4,
    warmup_steps=200,
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/900000 [00:00<?, ? examples/s]

Map:   0%|          | 0/100001 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Fine-tuned model saved to /content/drive/MyDrive/S2026/CS 274/Playlist-Recommender/fuzzy_finetuned_model

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
import os

# Load pruned clusters (hard assignments via argmax)
clusters_pruned_df = pd.read_csv(
    os.path.join(CLUSTERS_OUTPUT_DIR, "fkmeans_clusters_pruned.csv"),
    dtype={"pid": str},
)

clusters_pruned_df.head()

  pid  cluster
0   2       18
1   5       13
2   7       13
3  10       13
4  20       39

In [5]:
# Identify the cluster column (assuming it's the one that isn't 'pid')
cluster_col = [c for c in clusters_pruned_df.columns if c != "pid"][0]
print(f"Using column '{cluster_col}' for hard cluster assignments.")

# Ensure playlist_titles is loaded
if 'playlist_titles' not in globals():
    import pickle
    print("Loading playlist_titles...")
    with open(EMBEDDINGS_PKL, "rb") as f:
        raw_data = pickle.load(f)
    playlist_titles = (
        raw_data.get("playlist_titles", {})
        if isinstance(raw_data, dict)
        else {}
    )

# Map pids to titles
data_pruned_df = pd.DataFrame({
    "Playlist Title": [playlist_titles.get(pid, "") for pid in clusters_pruned_df["pid"]],
    "Cluster Labels": clusters_pruned_df[cluster_col]
})

# Drop untitled playlists
data_pruned_df = data_pruned_df[data_pruned_df["Playlist Title"].str.strip() != ""].reset_index(drop=True)

# Train/val split
train_pruned_df, val_pruned_df = train_test_split(data_pruned_df, test_size=0.1, random_state=42)

TRAIN_PRUNED_CSV = os.path.join(CLUSTERS_OUTPUT_DIR, "train_pruned_hard.csv")
VAL_PRUNED_CSV   = os.path.join(CLUSTERS_OUTPUT_DIR, "val_pruned_hard.csv")

train_pruned_df.to_csv(TRAIN_PRUNED_CSV, index=False)
val_pruned_df.to_csv(VAL_PRUNED_CSV, index=False)
print(f"Prepared hard cluster dataset. Train: {len(train_pruned_df)}  Val: {len(val_pruned_df)}")

# Display the dataset with titles to verify
display(data_pruned_df.head())

Using column 'cluster' for hard cluster assignments.
Loading playlist_titles...
Prepared hard cluster dataset. Train: 266860  Val: 29652

  Playlist Title  Cluster Labels
0        korean               18
1        Wedding              13
2           2017              13
3          abby               13
4        mixtape              39

In [10]:
ft_hard_path = os.path.join(
    REPO_DIR, "PlaylistRecsysUpgrade", "finetuning", "hardfinetuning_crossentropy.py"
)
spec   = importlib.util.spec_from_file_location("hardfinetuning_crossentropy", ft_hard_path)
hard_ft = importlib.util.module_from_spec(spec)
spec.loader.exec_module(hard_ft)
print("hardfinetuning_crossentropy loaded.")

hardfinetuning_crossentropy loaded.

In [11]:
# Fine-tune on the pruned dataset with MiniLM
FINETUNED_PRUNED_MODEL_DIR = f"{PROJECT_BASE}/fuzzy_finetuned_model_pruned_minilm"
os.makedirs(FINETUNED_PRUNED_MODEL_DIR, exist_ok=True)

hard_ft.run(
    train_csv=TRAIN_PRUNED_CSV,
    val_csv=VAL_PRUNED_CSV,
    output_dir=FINETUNED_PRUNED_MODEL_DIR,
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    batch_size=128,
    epochs=20,
    learning_rate=3e-4,
    warmup_steps=200,
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/266860 [00:00<?, ? examples/s]

Map:   0%|          | 0/29652 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Fine-tuned model saved to /content/drive/MyDrive/S2026/CS 274/Playlist-Recommender/fuzzy_finetuned_model_pruned_minilm